(ns emorogue.tables)

(def items-table
  [{:name "money-bag"}
   {:name "baguette-bread"}
   {:name "pizza"}
   {:name "pizza"}
   {:name "sushi"}])

(def people-table
  {})

(def names-table
  {:m ["james"
       "john"
       "robert"
       "michael"
       "william"
       "david"
       "richard"
       "joseph"
       "thomas"
       "charles"]
   :f ["mary"
       "patricia"
       "jennifer"
       "linda"
       "elizabeth"
       "barbara"
       "susan"
       "jessica"
       "sarah"
       "karen"]})

(def sentence-table
  {:verb ["launches into"
          "emits"
          "spews forth"
          "begins"
          "addresses"
          "vomits up"
          "communicates"
          "orates"
          "utters"
          "verbalizes"
          "comes out with"
          "alleges"
          "voices"
          "states"
          "suggests"
          "tells of"
          "reports"
          "claims"
          "sidles up with"
          "sneaks out"
          "delivers"
          "discloses"
          "maintains"
          "reveals"
          "implies"
          "expresses"
          "declares"
          "conveys"
          "announces"
          "gives voice to"
          "puts into words"
          "puts forth"
          "riffs upon"
          "recites"
          "rehearses"
          "begins remarks with"
          "divulges"
          "cojectures"
          "gabs about with"
          "enunciates"
          "vocalizes"
          "makes known"
          "makes public"
          "pops off"
          "yaks out"
          "spills"
          "mumbles"
          "murmurs"
          "mutters"
          "modulates"
          "gasbags"
          "avers"
          "blabs"
          "chews over"
          "shouts out"
          "yells out"
          "growls"
          "grinds down"
          "chatters"
          "trots out"
          "drawls out"
          "enunciates"
          "articulates"
          "proclaims"
          "exclaims"
          "recounts"
          "expatiates"]
   :adjective ["brutal"
               "gut wrenching"
               "ham-fisted"
               "vicious"
               "merciless"
               "ferocious"
               "callous"
               "barbarous"
               "harsh"
               "inhuman"
               "rude"
               "rough"
               "savage"
               "severe"
               "bloodthirsty"
               "insensitive"
               "uncivil"
               "unfeeling"
               "unmannerly"
               "unmerciful"
               "remorseless"
               "pitiless"
               "hard"
               "impolite"
               "languid"
               "vigorous"
               "glorious"
               "dazzling"
               "delightful"
               "enjoyable"
               "gorgeous"
               "grand"
               "gratifying"
               "beautiful"
               "bright"
               "brilliant"
               "heroic"
               "great"
               "illustrious"
               "snarling"
               "noble"
               "magnificent"
               "memorable"
               "marvelous"
               "remarkable"
               "shining"
               "splendid"
               "sublime"
               "superb"
               "triumphant"
               "wonderful"
               "august"
               "celebrated"
               "distinguished"
               "effulgent"
               "elevated"
               "heavenly"
               "fine"
               "famed"
               "eminent"
               "esteemed"
               "exalted"
               "excellent"
               "honorable"
               "immortal"
               "majestic"
               "notable"
               "pleasureable"
               "preeminent"
               "radiant"
               "renowned"
               "resplendent"
               "time-honored"
               "venerable"
               "well-known"
               "much treaded"
               "clumsy"
               "bungling"
               "heavy-handed"
               "bulky"
               "ponderous"
               "ungainly"
               "inept"
               "all thumbs"
               "blundering"
               "blunderous"
               "bumbling"
               "butterfingered"
               "ill-shaped"
               "oafish"
               "untalented"
               "stumbling"
               "uncouth"
               "uncoordinated"
               "helpless"
               "heavy"
               "inelegant"
               "inexperienced"
               "gawky"
               "gauche"
               "crude"
               "graceless"
               "sub-par"]
:noun ["monologue"
       "treatise"
       "discussion"
       "exposition"
       "commentary"
       "discourse"
       "dissertation"
       "memoir"
       "thesis"
       "argument"
       "inquisition"
       "disquisition"
       "review"
       "lecture"
       "speech"
       "soliloquy"
       "stand-up bit"
       "talk"]
:subject ["the weather"
          "sports science"
          "the history of venice"
          "ancient egypt"
          "gardening"
          "how to grow tubers"
          "race politics"
          "18th century italian politics"
          "materials"
          "the physics of tubas"
          "the natural sciences"
          "computer science"
          "unladen swallows"
          "the architecture of clouds"
          "the flight of bees"
          "world war one history"
          "world war two history"
          "the war of the roses"
          "constitutional monarchy"
          "libertarian socialism"
          "a one way ticket to temporary psychosis"
          "the battle of hastings"
          "the fall of great empires"
          "the impact of karl marx"
          "american art in the 20th century"
          "life before the invention of photography"
          "the canadian history of film"
          "the economics of europe after world war one"
          "fashion in the 17th century"
          "17th century shite-posting"
          "the sound of carl sagan's voice"
          "ugh, hippie culture"
          "new wave music"
          "dolphins"
          "the positive qualities of propaganda films"
          "the justifications for nuclear war"
          "trade unions"
          "the history of japanese isolationism"
          "the carnation revolution"
          "the yalta conference"
          "british colonization of india"
          "british colonization of africa"
          "british colonization of uranus"
          "the golden age of piracy"
          "the evolution of flight"
          "historical events predicted in fiction"
          "julius caesar"
          "aztec life before the arrival of colonists"
          "agriarianism"
          "the 1960s aesthetic"
          "medieval medicine"
          "incorrect quantumn physics"
          "pandemics that changed history"
          "the history of australia"
          "czechoslovakian jazz"
          "elliptic curve cryptography"
          "the history of punk subculture"
          "cypherpunk heroes"
          "the greek dark ages"
          "chivalry"
          "the museum aesthetic"
          "an incomplete history of berserkers"
          "whale song"
          ]})

